### ISSUE TITLE
Generate slugs from club titles in JSON file and append to each club entry

### ISSUE THREAD

**Issue by aomi** [VikeLabs/ClubsDirectory#44]
Given a single club object:
```json
{
    "id": "1",
    "name": "UVic Drama and Musical Theatre Club",
 ... omiited
}
```
using the `name` property, generated a `slug` field on the same level using a script. I would suggest using some slugify package as a dev dependency and creating a script under `scripts/slugify.js` that would create a object like the following:

The script should only edit the `slug` property and output to console for flexibility in usage. 

The slugs should be URL-friendly and not require any escape characters etc. 

```json
{
    "id": "1",
    "name": "UVic Drama and Musical Theatre Club",
    "slug": "uvic-drama-and-musical-theatre-club",
 ... omiited
}

**Comment by aomi** [comment]
Resolves some of the issues mentioned in https://github.com/VikeLabs/ClubsDirectory/issues/39 and https://github.com/VikeLabs/ClubsDirectory/pull/43

**Comment by malcolmseyd** [comment]
Closing since PR #45 was merged
